export const Global_countries = [
     { label: 'Afghanistan', value: '1'},
     { label: 'Albania', value: '2'},
     { label: 'Algeria', value: '3'},
     { label: 'Andorra', value: '4'},
     { label: 'Angola', value: '5'},
     { label: 'Antigua and Barbuda', value: '6'},
     { label: 'Argentina', value: '7'},
     { label: 'Armenia', value: '8'},
     { label: 'Australia', value: '9'},
     { label: 'Austria', value: '10'},
     { label: 'Azerbaijan', value: '11'},
     { label: 'Bahamas', value: '12'},
     { label: 'Bahrain', value: '13'},
     { label: 'Bangladesh', value: '14'},
     { label: 'Barbados', value: '15'},
     { label: 'Belarus', value: '16'},
     { label: 'Belgium', value: '17'},
     { label: 'Belize', value: '18'},
     { label: 'Benin', value: '19'},
     { label: 'Bhutan', value: '20'},
     { label: 'Bolivia', value: '21'},
     { label: 'Bosnia and Herzegovina', value: '22'},
     { label: 'Botswana', value: '23'},
     { label: 'Brazil', value: '24'},
     { label: 'Brunei', value: '25'},
     { label: 'Bulgaria', value: '26'},
     { label: 'Burkina Faso', value: '27'},
     { label: 'Burundi', value: '28'},
     { label: 'Cabo Verde', value: '29'},
     { label: 'Cambodia', value: '30'},
     { label: 'Cameroon', value: '31'},
     { label: 'Canada', value: '32'},
     { label: 'Central African Republic', value: '33'},
     { label: 'Chad', value: '34'},
     { label: 'Chile', value: '35'},
     { label: 'China', value: '36'},
     { label: 'Colombia', value: '37'},
     { label: 'Comoros', value: '38'},
     { label: 'Congo, Democratic Republic of the', value: '39'},
     { label: 'Congo, Republic of the', value: '40'},
     { label: 'Costa Rica', value: '41'},
     { label: 'Croatia', value: '42'},
     { label: 'Cuba', value: '43'},
     { label: 'Cyprus', value: '44'},
     { label: 'Czech Republic', value: '45'},
     { label: 'Denmark', value: '46'},
     { label: 'Djibouti', value: '47'},
     { label: 'Dominica', value: '48'},
     { label: 'Dominican Republic', value: '49'},
     { label: 'Ecuador', value: '50'},
     { label: 'Egypt', value: '51'},
     { label: 'El Salvador', value: '52'},
     { label: 'Equatorial Guinea', value: '53'},
     { label: 'Eritrea', value: '54'},
     { label: 'Estonia', value: '55'},
     { label: 'Eswatini', value: '56'},
     { label: 'Ethiopia', value: '57'},
     { label: 'Fiji', value: '58'},
     { label: 'Finland', value: '59'},
     { label: 'France', value: '60'},
     { label: 'Gabon', value: '61'},
     { label: 'Gambia', value: '62'},
     { label: 'Georgia', value: '63'},
     { label: 'Germany', value: '64'},
     { label: 'Ghana', value: '65'},
     { label: 'Greece', value: '66'},
     { label: 'Grenada', value: '67'},
     { label: 'Guatemala', value: '68'},
     { label: 'Guinea', value: '69'},
     { label: 'Guinea-Bissau', value: '70'},
     { label: 'Guyana', value: '71'},
     { label: 'Haiti', value: '72'},
     { label: 'Honduras', value: '73'},
     { label: 'Hungary', value: '74'},
     { label: 'Iceland', value: '75'},
     { label: 'India', value: '76'},
     { label: 'Indonesia', value: '77'},
     { label: 'Iran', value: '78'},
     { label: 'Iraq', value: '79'},
     { label: 'Ireland', value: '80'},
     { label: 'Israel', value: '81'},
     { label: 'Italy', value: '82'},
     { label: 'Jamaica', value: '83'},
     { label: 'Japan', value: '84'},
     { label: 'Jordan', value: '85'},
     { label: 'Kazakhstan', value: '86'},
     { label: 'Kenya', value: '87'},
     { label: 'Kiribati', value: '88'},
     { label: 'Korea, North', value: '89'},
     { label: 'Korea, South', value: '90'},
     { label: 'Kosovo', value: '91'},
     { label: 'Kuwait', value: '92'},
     { label: 'Kyrgyzstan', value: '93'},
     { label: 'Laos', value: '94'},
     { label: 'Latvia', value: '95'},
     { label: 'Lebanon', value: '96'},
     { label: 'Lesotho', value: '97'},
     { label: 'Liberia', value: '98'},
     { label: 'Libya', value: '99'},
     { label: 'Liechtenstein', value: '100'},
     { label: 'Lithuania', value: '101'},
     { label: 'Luxembourg', value: '102'},
     { label: 'Madagascar', value: '103'},
     { label: 'Malawi', value: '104'},
     { label: 'Malaysia', value: '105'},
     { label: 'Maldives', value: '106'},
     { label: 'Mali', value: '107'},
     { label: 'Malta', value: '108'},
     { label: 'Marshall Islands', value: '109'},
     { label: 'Mauritania', value: '110'},
     { label: 'Mauritius', value: '111'},
     { label: 'Mexico', value: '112'},
     { label: 'Micronesia', value: '113'},
     { label: 'Moldova', value: '114'},
     { label: 'Monaco', value: '115'},
     { label: 'Mongolia', value: '116'},
     { label: 'Montenegro', value: '117'},
     { label: 'Morocco', value: '118'},
     { label: 'Mozambique', value: '119'},
     { label: 'Myanmar', value: '120'},
     { label: 'Namibia', value: '121'},
     { label: 'Nauru', value: '122'},
     { label: 'Nepal', value: '123'},
     { label: 'Netherlands', value: '124'},
     { label: 'New Zealand', value: '125'},
     { label: 'Nicaragua', value: '126'},
     { label: 'Niger', value: '127'},
     { label: 'Nigeria', value: '128'},
     { label: 'North Macedonia', value: '129'},
     { label: 'Norway', value: '130'},
     { label: 'Oman', value: '131'},
     { label: 'Pakistan', value: '132'},
     { label: 'Palau', value: '133'},
     { label: 'Palestine', value: '134'},
     { label: 'Panama', value: '135'},
     { label: 'Papua New Guinea', value: '136'},
     { label: 'Paraguay', value: '137'},
     { label: 'Peru', value: '138'},
     { label: 'Philippines', value: '139'},
     { label: 'Poland', value: '140'},
     { label: 'Portugal', value: '141'},
     { label: 'Qatar', value: '142'},
     { label: 'Romania', value: '143'},
     { label: 'Russia', value: '144'},
     { label: 'Rwanda', value: '145'},
     { label: 'Saint Kitts and Nevis', value: '146'},
     { label: 'Saint Lucia', value: '147'},
     { label: 'Saint Vincent and the Grenadines', value: '148'},
     { label: 'Samoa', value: '149'},
     { label: 'San Marino', value: '150'},
     { label: 'Sao Tome and Principe', value: '151'},
     { label: 'Saudi Arabia', value: '152'},
     { label: 'Senegal', value: '153'},
     { label: 'Serbia', value: '154'},
     { label: 'Seychelles', value: '155'},
     { label: 'Sierra Leone', value: '156'},
     { label: 'Singapore', value: '157'},
     { label: 'Slovakia', value: '158'},
     { label: 'Slovenia', value: '159'},
     { label: 'Solomon Islands', value: '160'},
     { label: 'Somalia', value: '161'},
     { label: 'South Africa', value: '162'},
     { label: 'South Sudan', value: '163'},
     { label: 'Spain', value: '164'},
     { label: 'Sri Lanka', value: '165'},
     { label: 'Sudan', value: '166'},
     { label: 'Suriname', value: '167'},
     { label: 'Sweden', value: '168'},
     { label: 'Switzerland', value: '169'},
     { label: 'Syria', value: '170'},
     { label: 'Taiwan', value: '171'},
     { label: 'Tajikistan', value: '172'},
     { label: 'Tanzania', value: '173'},
     { label: 'Thailand', value: '174'},
     { label: 'Timor-Leste', value: '175'},
     { label: 'Turkey', value: '176'},
     { label: 'Turkmenistan', value: '177'},
     { label: 'Tuvalu', value: '178'},
     { label: 'Uganda', value: '179'},
     { label: 'Ukraine', value: '180'},
     { label: 'United Arab Emirates', value: '181'},
     { label: 'United Kingdom', value: '182'},
     { label: 'United States', value: '183'},
     { label: 'Uruguay', value: '184'},
     { label: 'Uzbekistan', value: '185'},
     { label: 'Vanuatu', value: '186'},
     { label: 'Vatican City', value: '187'},
     { label: 'Venezuela', value: '188'},
     { label: 'Vietnam', value: '189'},
     { label: 'Yemen', value: '190'},
     { label: 'Zambia', value: '191'},
     { label: 'Zimbabwe', value: '192'},
]


export const India_states = [
     { label: 'Andhra Pradesh', value: '1'},
     { label: 'Arunachal Pradesh', value: '2'},
     { label: 'Assam', value: '3'},
     { label: 'Bihar', value: '4'},
     { label: 'Chhattisgarh', value: '5'},
     { label: 'Goa', value: '6'},
     { label: 'Gujarat', value: '7'},
     { label: 'Haryana', value: '8'},
     { label: 'Himachal Pradesh', value: '9'},
     { label: 'Jharkhand', value: '10'},
     { label: 'Karnataka', value: '11'},
     { label: 'Kerala', value: '12'},
     { label: 'Madhya Pradesh', value: '13'},
     { label: 'Maharashtra', value: '14'},
     { label: 'Manipur', value: '15'},
     { label: 'Meghalaya', value: '16'},
     { label: 'Mizoram', value: '17'},
     { label: 'Nagaland', value: '18'},
     { label: 'Odisha', value: '19'},
     { label: 'Punjab', value: '20'},
     { label: 'Rajasthan', value: '21'},
     { label: 'Sikkim', value: '22'},
     { label: 'Tamil Nadu', value: '23'},
     { label: 'Telangana', value: '24'},
     { label: 'Tripura', value: '25'},
     { label: 'Uttar Pradesh', value: '26'},
     { label: 'Uttarakhand', value: '27'},
     { label: 'West Bengal', value: '28'},
   ];

export const Gujarat_cities = [
     { label: 'Ahmedabad', value: '1'},
     { label: 'Surat', value: '2'},
     { label: 'Vadodara', value: '3'},
     { label: 'Rajkot', value: '4'},
     { label: 'Gandhinagar', value: '5'},
     { label: 'Jamnagar', value: '6'},
     { label: 'Junagadh', value: '7'},
     { label: 'Bhuj', value: '8'},
     { label: 'Anand', value: '9'},
     { label: 'Nadiad', value: '10'},
     { label: 'Mehsana', value: '11'},
     { label: 'Porbandar', value: '12'},
     { label: 'Vapi', value: '13'},
     { label: 'Valsad', value: '14'},
     { label: 'Gandhidham', value: '15'},
     { label: 'Patan', value: '16'},
     { label: 'Daman', value: '17'},
     { label: 'Navsari', value: '18'},
     { label: 'Kheda', value: '19'},
     { label: 'Palitana', value: '20'},
     { label: 'Rajula', value: '21'},
     { label: 'Modasa', value: '22'},
     { label: 'Bilimora', value: '23'},
     { label: 'Bharuch', value: '24'},
     { label: 'Dahod', value: '25'},
     { label: 'Godhra', value: '26'},
     { label: 'Suratgarh', value: '27'},
     { label: 'Upleta', value: '28'},
     { label: 'Wankaner', value: '29'},
     { label: 'Palanpur', value: '30'},
     { label: 'Bhavnagar', value: '31'},
     { label: 'Amreli', value: '32'},
     { label: 'Dang', value: '33'},
     { label: 'Kapadvanj', value: '34'},
     { label: 'Khambhalia', value: '35'},
     { label: 'Chotila', value: '36'},
     { label: 'Dholka', value: '37'},
     { label: 'Halol', value: '38'},
     { label: 'Mahesana', value: '39'},
     { label: 'Sanand', value: '40'},
     { label: 'Talaja', value: '41'},
     { label: 'Vijapur', value: '42'},
     { label: 'Jambusar', value: '43'},
     { label: 'Kutch', value: '44'},
     { label: 'Mandvi', value: '45'},
     { label: 'Radhanpur', value: '46'},
]